//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmotionsRecognition
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full
    {
        public Nullable<double> Number { get; set; }
        public string EnglishSentence { get; set; }
        public string PolishSentence { get; set; }
        public Nullable<double> F4 { get; set; }
        public Nullable<double> F5 { get; set; }
        public Nullable<double> ValenceAll { get; set; }
        public Nullable<double> ArousalAll { get; set; }
        public Nullable<double> DominanceAll { get; set; }
        public Nullable<double> OriginAll { get; set; }
        public Nullable<double> SignificanceAll { get; set; }
        public Nullable<double> SourceAll { get; set; }
        public Nullable<double> Valence_Main_Sample { get; set; }
        public Nullable<double> Valence_Main_Sample1 { get; set; }
        public Nullable<double> Valence_Main_Sample2 { get; set; }
        public Nullable<double> Valence_Main_Sample3 { get; set; }
        public Nullable<double> Valence_Main_Sample4 { get; set; }
        public Nullable<double> Valence_Main_Sample_Female { get; set; }
        public Nullable<double> Valence_Main_Sample_Female1 { get; set; }
        public Nullable<double> Valence_Main_Sample_Female2 { get; set; }
        public Nullable<double> Valence_Main_Sample_Female3 { get; set; }
        public Nullable<double> Valence_Main_Sample_Female4 { get; set; }
        public Nullable<double> Valence_Main_Sample_Male { get; set; }
        public Nullable<double> Valence_Main_Sample_Male1 { get; set; }
        public Nullable<double> Valence_Main_Sample_Male2 { get; set; }
        public Nullable<double> Valence_Main_Sample_Male3 { get; set; }
        public Nullable<double> Valence_Main_Sample_Male4 { get; set; }
        public Nullable<double> Valence_psych { get; set; }
        public Nullable<double> Valence_psych1 { get; set; }
        public Nullable<double> Valence_psych2 { get; set; }
        public Nullable<double> Valence_psych3 { get; set; }
        public Nullable<double> Valence_psych4 { get; set; }
        public Nullable<double> Arousal_Main_Sample { get; set; }
        public Nullable<double> Arousal_Main_Sample1 { get; set; }
        public Nullable<double> Arousal_Main_Sample2 { get; set; }
        public Nullable<double> Arousal_Main_Sample3 { get; set; }
        public Nullable<double> Arousal_Main_Sample4 { get; set; }
        public Nullable<double> Arousal_Main_Sample_Female { get; set; }
        public Nullable<double> Arousal_Main_Sample_Female1 { get; set; }
        public Nullable<double> Arousal_Main_Sample_Female2 { get; set; }
        public Nullable<double> Arousal_Main_Sample_Female3 { get; set; }
        public Nullable<double> Arousal_Main_Sample_Female4 { get; set; }
        public Nullable<double> Arousal_Main_Sample__Male { get; set; }
        public Nullable<double> Arousal_Main_Sample__Male1 { get; set; }
        public Nullable<double> Arousal_Main_Sample__Male2 { get; set; }
        public Nullable<double> Arousal_Main_Sample__Male3 { get; set; }
        public Nullable<double> Arousal_Main_Sample__Male4 { get; set; }
        public Nullable<double> Arousal_psych { get; set; }
        public Nullable<double> Arousal_psych1 { get; set; }
        public Nullable<double> Arousal_psych2 { get; set; }
        public Nullable<double> Arousal_psych3 { get; set; }
        public Nullable<double> Arousal_psych4 { get; set; }
        public Nullable<double> Dominance_Main_Sample { get; set; }
        public Nullable<double> Dominance_Main_Sample1 { get; set; }
        public Nullable<double> Dominance_Main_Sample2 { get; set; }
        public Nullable<double> Dominance_Main_Sample3 { get; set; }
        public Nullable<double> Dominance_Main_Sample4 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Female { get; set; }
        public Nullable<double> Dominance_Main_Sample_Female1 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Female2 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Female3 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Female4 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Male { get; set; }
        public Nullable<double> Dominance_Main_Sample_Male1 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Male2 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Male3 { get; set; }
        public Nullable<double> Dominance_Main_Sample_Male4 { get; set; }
        public Nullable<double> Dominance_psych { get; set; }
        public Nullable<double> Dominance_psych1 { get; set; }
        public Nullable<double> Dominance_psych2 { get; set; }
        public Nullable<double> Dominance_psych3 { get; set; }
        public Nullable<double> Dominance_psych4 { get; set; }
        public Nullable<double> Origin_Main_Sample { get; set; }
        public Nullable<double> Origin_Main_Sample1 { get; set; }
        public Nullable<double> Origin_Main_Sample2 { get; set; }
        public Nullable<double> Origin_Main_Sample3 { get; set; }
        public Nullable<double> Origin_Main_Sample4 { get; set; }
        public Nullable<double> Origin_Main_Sample_Female { get; set; }
        public Nullable<double> Origin_Main_Sample_Female1 { get; set; }
        public Nullable<double> Origin_Main_Sample_Female2 { get; set; }
        public Nullable<double> Origin_Main_Sample_Female3 { get; set; }
        public Nullable<double> Origin_Main_Sample_Female4 { get; set; }
        public Nullable<double> Origin_Main_Sample_Male { get; set; }
        public Nullable<double> Origin_Main_Sample_Male1 { get; set; }
        public Nullable<double> Origin_Main_Sample_Male2 { get; set; }
        public Nullable<double> Origin_Main_Sample_Male3 { get; set; }
        public Nullable<double> Origin_Main_Sample_Male4 { get; set; }
        public Nullable<double> Origin_psych { get; set; }
        public Nullable<double> Origin_psych1 { get; set; }
        public Nullable<double> Origin_psych2 { get; set; }
        public Nullable<double> Origin_psych3 { get; set; }
        public Nullable<double> Origin_psych4 { get; set; }
        public Nullable<double> Significance_Main_Sample { get; set; }
        public Nullable<double> Significance_Main_Sample1 { get; set; }
        public Nullable<double> Significance_Main_Sample2 { get; set; }
        public Nullable<double> Significance_Main_Sample3 { get; set; }
        public Nullable<double> Significance_Main_Sample4 { get; set; }
        public Nullable<double> Significance_Main_Sample_Female { get; set; }
        public Nullable<double> Significance_Main_Sample_Female1 { get; set; }
        public Nullable<double> Significance_Main_Sample_Female2 { get; set; }
        public Nullable<double> Significance_Main_Sample_Female3 { get; set; }
        public Nullable<double> Significance_Main_Sample_Female4 { get; set; }
        public Nullable<double> Significance_Main_Sample_Male { get; set; }
        public Nullable<double> Significance_Main_Sample_Male1 { get; set; }
        public Nullable<double> Significance_Main_Sample_Male2 { get; set; }
        public Nullable<double> Significance_Main_Sample_Male3 { get; set; }
        public Nullable<double> Significance_Main_Sample_Male4 { get; set; }
        public Nullable<double> Significance_psych { get; set; }
        public Nullable<double> Significance_psych1 { get; set; }
        public Nullable<double> Significance_psych2 { get; set; }
        public Nullable<double> Significance_psych3 { get; set; }
        public Nullable<double> Significance_psych4 { get; set; }
        public Nullable<double> Source_Main_Sample { get; set; }
        public Nullable<double> Source_Main_Sample1 { get; set; }
        public Nullable<double> Source_Main_Sample2 { get; set; }
        public Nullable<double> Source_Main_Sample3 { get; set; }
        public Nullable<double> Source_Main_Sample4 { get; set; }
        public Nullable<double> Source_Main_Sample_Female { get; set; }
        public Nullable<double> Source_Main_Sample_Female1 { get; set; }
        public Nullable<double> Source_Main_Sample_Female2 { get; set; }
        public Nullable<double> Source_Main_Sample_Female3 { get; set; }
        public Nullable<double> Source_Main_Sample_Female4 { get; set; }
        public Nullable<double> Source_Main_Sample_Male { get; set; }
        public Nullable<double> Source_Main_Sample_Male1 { get; set; }
        public Nullable<double> Source_Main_Sample_Male2 { get; set; }
        public Nullable<double> Source_Main_Sample_Male3 { get; set; }
        public Nullable<double> Source_Main_Sample_Male4 { get; set; }
        public Nullable<double> Source_psych { get; set; }
        public Nullable<double> Source_psych1 { get; set; }
        public Nullable<double> Source_psych2 { get; set; }
        public Nullable<double> Source_psych3 { get; set; }
        public Nullable<double> Source_psych4 { get; set; }
        public Nullable<double> F132 { get; set; }
        public Nullable<double> F133 { get; set; }
        public Nullable<double> F134 { get; set; }
        public Nullable<double> F135 { get; set; }
        public Nullable<double> F136 { get; set; }
        public Nullable<double> F137 { get; set; }
        public Nullable<double> F138 { get; set; }
        public Nullable<double> F139 { get; set; }
        public Nullable<double> F140 { get; set; }
        public Nullable<double> F141 { get; set; }
        public string F142 { get; set; }
        public int ID { get; set; }
    }
}
