//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmotionsRecognition
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecognizedEmotion
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<float> Anger { get; set; }
        public Nullable<float> Contempt { get; set; }
        public Nullable<float> Disgust { get; set; }
        public Nullable<float> Fear { get; set; }
        public Nullable<float> Happiness { get; set; }
        public Nullable<float> Neutral { get; set; }
        public Nullable<float> Sadness { get; set; }
        public Nullable<float> Surprise { get; set; }
        public int TextID { get; set; }
    
        public virtual Text Text { get; set; }
    }
}
